export const styles = {
  container: {
    minHeight: '100vh',
    background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    padding: '20px',
    fontFamily: 'system-ui, -apple-system, sans-serif',
  },
  card: {
    maxWidth: '1200px',
    margin: '0 auto',
    background: 'white',
    borderRadius: '16px',
    padding: '30px',
    boxShadow: '0 20px 60px rgba(0,0,0,0.3)',
  },
  title: { fontSize: '28px', fontWeight: 'bold', color: '#333', marginBottom: '20px', textAlign: 'center' },
  formGroup: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: '15px', marginBottom: '20px' },
  inputGroup: { display: 'flex', flexDirection: 'column', gap: '8px' },
  label: { fontSize: '14px', fontWeight: '600', color: '#555' },
  input: { padding: '10px 12px', fontSize: '14px', border: '2px solid #ddd', borderRadius: '8px', outline: 'none', transition: 'all 0.2s' },
  buttonGroup: { display: 'flex', gap: '10px', flexWrap: 'wrap', marginBottom: '20px' },
  button: { flex: '1', minWidth: '150px', padding: '12px 20px', fontSize: '14px', fontWeight: '600', border: 'none', borderRadius: '8px', cursor: 'pointer', transition: 'all 0.2s' },
  buttonPrimary: { background: '#667eea', color: 'white' },
  buttonSuccess: { background: '#48bb78', color: 'white' },
  buttonWarning: { background: '#ed8936', color: 'white' },
  buttonDisabled: { background: '#cbd5e0', color: '#a0aec0', cursor: 'not-allowed' },
  toggleContainer: { display: 'flex', justifyContent: 'center', alignItems: 'center', gap: '20px', marginBottom: '15px', flexWrap: 'wrap' },
  toggleLabel: { display: 'flex', alignItems: 'center', gap: '8px', cursor: 'pointer' },
  checkbox: { width: '18px', height: '18px', cursor: 'pointer' },
  toggleText: { fontSize: '14px', fontWeight: '600', color: '#555' },
  folderInfo: { fontSize: '13px', color: '#667eea', padding: '6px 12px', background: '#eef2ff', borderRadius: '6px' },
  statusBadge: { padding: '10px 15px', borderRadius: '8px', textAlign: 'center', fontSize: '14px', fontWeight: '600', marginBottom: '15px', background: '#e2e8f0', color: '#2d3748' },
  statusSuccess: { background: '#c6f6d5', color: '#22543d' },
  statusError: { background: '#fed7d7', color: '#742a2a' },
  outputSection: { marginBottom: '20px' },
  jsonOutput: { background: '#1a202c', color: '#e2e8f0', padding: '15px', borderRadius: '8px', fontSize: '13px', maxHeight: '300px', overflow: 'auto', whiteSpace: 'pre-wrap', wordBreak: 'break-word' },
  debugSection: { marginBottom: '20px' },
  debugSummary: { cursor: 'pointer', fontSize: '14px', fontWeight: '600', color: '#667eea', padding: '10px', background: '#f7fafc', borderRadius: '8px' },
  debugContent: { background: '#f7fafc', padding: '10px', fontSize: '12px', maxHeight: '200px', overflow: 'auto', borderRadius: '8px', marginTop: '10px' },
  batchSection: { marginTop: '30px', padding: '20px', background: '#f7fafc', borderRadius: '12px' },
  sectionHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '20px', flexWrap: 'wrap', gap: '15px' },
  sectionTitle: { fontSize: '20px', fontWeight: 'bold', color: '#333' },
  fileInputLabel: { display: 'flex', alignItems: 'center', gap: '8px', padding: '10px 20px', background: '#667eea', color: 'white', borderRadius: '8px', cursor: 'pointer', fontSize: '14px', fontWeight: '600', transition: 'all 0.2s' },
  uploadIcon: { fontSize: '18px' },
  uploadText: {},
  fileInput: { display: 'none' },
  batchInfo: { marginTop: '20px' },
  statsContainer: { display: 'flex', justifyContent: 'space-around', gap: '15px', marginBottom: '15px', flexWrap: 'wrap' },
  statItem: { display: 'flex', alignItems: 'center', gap: '8px', padding: '10px 15px', background: 'white', borderRadius: '8px', boxShadow: '0 2px 4px rgba(0,0,0,0.1)' },
  statIcon: { fontSize: '20px' },
  statLabel: { fontSize: '14px', color: '#718096' },
  statValue: { fontSize: '18px', fontWeight: 'bold', color: '#2d3748' },
  tableContainer: { marginTop: '20px', overflowX: 'auto', borderRadius: '8px', border: '1px solid #e2e8f0' },
  table: { width: '100%', borderCollapse: 'collapse', background: 'white' },
  tableHeaderRow: { background: '#edf2f7' },
  tableHeader: { padding: '12px', textAlign: 'left', fontSize: '14px', fontWeight: '600', color: '#2d3748', borderBottom: '2px solid #cbd5e0' },
  tableRow: { borderBottom: '1px solid #e2e8f0', transition: 'background 0.2s' },
  tableRowActive: { background: '#fef5e7', fontWeight: '600' },
  tableCell: { padding: '12px', fontSize: '14px', color: '#4a5568' },
  statusIndicator: { padding: '4px 12px', borderRadius: '12px', fontSize: '13px', fontWeight: '600', display: 'inline-block' },
  statusCompleted: { background: '#c6f6d5', color: '#22543d' },
  statusProcessing: { background: '#fef5e7', color: '#c05621' },
  statusPending: { background: '#e2e8f0', color: '#718096' },
};